#pragma config(Sensor, in1,    baseGyro,       sensorGyro)
#pragma config(Sensor, in3,    mogoPot,        sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in5,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in6,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, in7,    vbPot,          sensorPotentiometer)
#pragma config(Sensor, in8,    navPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  towerPing,      sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl12, button,         sensorTouch)
#pragma config(Motor,  port1,           intake,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           rightFrontBase, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftFrontBase, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftBackBase,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightBackBase, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mobile,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          elevator,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)
// Select Download method as "competition"
#pragma competitionControl(Competition)
//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

///////////////////////////////////////////////////
int autonNum = 1;
// RED  POLE     == 0 //
// RED  RIGHT1   == 1 //
// RED  LEFT1    == 2 //
// BLUE POLE     == 3 //
// BLUE RIGHT1   == 4 //
// BLUE LEFT1    == 5 //
// SKILLS        == 6 //
// BLUE RIGHT2   == 7 //
// RED  RIGHT2   == 8 //
// BLUE LEFT2    == 9 //
// RED  LEFT2    == 10//
///////////////////////////////////////////////////

#include "LCDCode_aryaJF3.h"
//#include "autonCode_aryaJF3.h"
//#include "driverCode_aryaJF3.h"
/*---------------------------------------------------------------------------*/
/*                            Pre-Autonomous Task                            */
/*---------------------------------------------------------------------------*/
void pre_auton()
{
	clearLCD();
	SensorValue[gyro] = 0;
	SensorValue[baseGyro] = 0;
	clearEncoders();
	clearTimer(T1);
	LCDRun();
}
/*---------------------------------------------------------------------------*/
/*                               Autonomous Task                             */
/*---------------------------------------------------------------------------*/
task autonomous()
{
	autonRun(autonNum);
}
/*---------------------------------------------------------------------------*/
/*                              User Control Task                            */
/*---------------------------------------------------------------------------*/
task usercontrol()
{
	bLCDBacklight = false;
	clearLCD();
	SensorValue[gyro] = 0;
	clearEncoders();
	clearTimer(T1);
	while (true)
	{
		base(vexRT[Ch3], vexRT[Ch2]); //base(int leftSpeed, int rightSpeed)
		mobileGoal(127, 0);           //mobileGoal(int speed, int hold)
		intakeClaw(127, 10);          //intakeClaw(int speed, int hold)
		liftUserControl(127, 15);     //liftUserControl(int speed, int hold)
		vbUserControl(127, 15);       //vbUserControl(int speed, int hold)


		LCDRun();
		//tipWarning();
	}
}
