#pragma config(Sensor, in3,    navPot,         sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in5,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in6,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  towerPing,      sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMiddle,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftOne,       tmotorNone, openLoop)
#pragma config(Motor,  port6,           liftTwo,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightMiddle,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightBack,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                          Upload photos and plexi glass                                 */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
bool LCDState = false;
string mainBattery, backupBattery;
int autonNum = 2;   ////////////////////////////////Default AUTON
int stateCheck = 0;
int soundCheck = 0;


void clearLCD()
{
	clearLCDLine(0);
	clearLCDLine(1);
}

void clearSound()
{
	wait1Msec(500);
	clearSounds();
}

void testSound()
{
	if(stateCheck != soundCheck)
	{
		playSound(soundShortBlip);
		soundCheck = stateCheck;
	}
	else
	{
		wait1Msec(100);
		clearSounds();
	}
}



void LCDRun()
{
	if(nLCDButtons == leftButton)
	{
		LCDState = true;
		bLCDBacklight = true;
		playSound(soundUpwardTones);
		wait1Msec(500);
		clearSounds();
	}
	if(LCDState == true)
	{

		if(SensorValue[navPot] <= 500)
		{
			testSound();
			stateCheck = 0;

			displayLCDCenteredString(0,"==              ");
			displayLCDCenteredString(1,"    RED POLE   >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 0;
				displayLCDCenteredString(0,"----RED POLE----");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound();
				wait1Msec(2000);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound();
			}
		}
		else if(SensorValue[navPot] >= 500 && SensorValue[navPot] <= 1000 )
		{
			testSound();
			stateCheck = 1;

			displayLCDCenteredString(0,"  ==            ");
			displayLCDCenteredString(1,"<  RED  RIGHT  >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 1;
				displayLCDCenteredString(0,"---RED  RIGHT---");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound();
				wait1Msec(2000);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound();
			}
		}
		else if(SensorValue[navPot] >= 1000 && SensorValue[navPot] <= 1500 )
		{
			stateCheck = 2;
			testSound();
			displayLCDCenteredString(0,"    ==          ");
			displayLCDCenteredString(1,"<   RED LEFT   >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 2;
				displayLCDCenteredString(0,"----RED LEFT----");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound();
				wait1Msec(2000);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound();
			}
		}
		else if(SensorValue[navPot] >= 1500 && SensorValue[navPot] <= 2000 )
		{
			stateCheck = 3;
			testSound();
			displayLCDCenteredString(0,"      ==        ");
			displayLCDCenteredString(1,"<  BLUE  POLE  >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 3;
				displayLCDCenteredString(0,"---BLUE  POLE---");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound();
				wait1Msec(2000);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound();
			}
		}
		else if(SensorValue[navPot] >= 2000 && SensorValue[navPot] <= 2500 )
		{
			stateCheck = 4;
			testSound();
			displayLCDCenteredString(0,"        ==      ");
			displayLCDCenteredString(1,"<  BLUE RIGHT  >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 4;
				displayLCDCenteredString(0,"---BLUE RIGHT---");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound();
				wait1Msec(2000);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound();
			}
		}
		else if(SensorValue[navPot] >= 2500 && SensorValue[navPot] <= 3000 )
		{
			stateCheck = 5;
			testSound();
			displayLCDCenteredString(0,"          ==    ");
			displayLCDCenteredString(1,"<  BLUE  LEFT  >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 5;
				displayLCDCenteredString(0,"---BLUE  LEFT---");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound();
				wait1Msec(2000);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound();
			}
		}
		else if(SensorValue[navPot] >= 3000 && SensorValue[navPot] <= 3500 )
		{
			stateCheck = 6;
			testSound();
			displayLCDCenteredString(0,"            ==  ");
			displayLCDCenteredString(1,"<    SKILLS    >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 6;
				displayLCDCenteredString(0,"-----SKILLS-----");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound();
				wait1Msec(2000);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound();
			}
		}
		else
		{
			stateCheck = 7;
			testSound();
			displayLCDCenteredString(0,"              ==");
			displayLCDCenteredString(1,"<    BATTERY    ");
			while(nLCDButtons == centerButton)
			{
				displayLCDString(0,0,"  Primary: ");

				sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
				displayNextLCDString(mainBattery);
				displayLCDCenteredString(1," ");
			}

		}
		if(nLCDButtons == rightButton)
		{
			LCDState = false;
			playSound(soundDownwardTones);
			wait1Msec(500);
			clearSounds();
		}
	}
	else
	{
		clearLCD();
		bLCDBacklight = false;
	}
}




//********************************************************************************************************//
//********************************************DRIVER_FUNCTIONS*********************************************//
//********************************************************************************************************//
void leftBase(int power)
{
	motor[leftFront] = power;
	motor[leftMiddle] = power;
	motor[leftBack] = power;
}
void rightBase(int power)
{
	motor[rightFront] = power;
	motor[rightMiddle] = power;
	motor[rightBack] = power;
}

void liftControl(int power)
{
	motor[liftOne] = power;
	motor[liftTwo] = power;
}
void base(bool setting, int duration, int speedLeft, int speedRight)//function to control base during auton and driver
{
	if(setting == 0) //Driver Code
	{
		leftBase( vexRT[Ch3]);
		rightBase(vexRT[Ch2]);
	}
	else
	{

	}
}

int mobilePickup = 0;
void lift(int upSpeed, int downSpeed, int hold)
{
	if(vexRT[Btn5U] == 1)
	{
		liftControl(upSpeed);
		mobilePickup = 0;
	}
	else if(vexRT[Btn5D] == 1)
	{
		liftControl(downSpeed);
		mobilePickup = 0;
	}
	else if(vexRT[Btn7U] == 1)
	{
		liftControl(upSpeed);
		mobilePickup = 1;
	}
	else if(vexRT[Btn7D] == 1)
	{
		liftControl(downSpeed+40);
		mobilePickup = 1;
	}
	else
	{
		if(SensorValue[liftPot] <= 1400 && mobilePickup == 0)
		{
			liftControl(hold-10);
		}
		else if(mobilePickup == 1)
		{
			liftControl(hold+15);
		}
		else
		{
			liftControl(hold);
		}
	}
}

void clawMove(int openSpeed, int closeSpeed, int hold)
{

	if(vexRT[Btn6U] == vexRT[Btn6D])
	{
		motor[claw] = hold;
	}
	else if(vexRT[Btn6U] == 1 && SensorValue[clawPot] >= 2400)
	{
		motor[claw] = openSpeed;
	}
	else if(vexRT[Btn6D] == 1  && SensorValue[clawPot] <= 3000)
	{
		clearTimer(T3);
		if(time1[T3] < 1000)
		{
			motor[claw] = closeSpeed;
		}
		else
		{
			motor[claw] = (hold - 10);
		}
	}
}

void autoLift(int upSpeed, int distance, int height, int hold, int timer)
{
	clearTimer(T2);
	if(vexRT[Btn8R] == 1)
	{
		while(SensorValue[towerPing] <= distance && time1[T2] < timer)
		{
			liftControl(upSpeed);
		}
	}
	if(vexRT[Btn8L] == 1)
	{
		while(SensorValue[liftPot] <= height && time1[T2] < timer)
		{
			liftControl(upSpeed);
		}
		while(SensorValue[liftPot] >= (height+300) && time1[T2] < timer)
		{
			liftControl(-upSpeed);
		}
	}
}





//********************************************************************************************************//
//********************************************AUTON_FUNCTIONS*********************************************//
//********************************************************************************************************//
//---Base---//:Controls the speed of the base motors.

void base(int rSpeed, int lSpeed)
{
	rightBase(rSpeed);
	leftBase(lSpeed);
}

void clearEncoders()
{
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
}
int leftDistance = (SensorValue[leftEncoder]/36000);
int rightDistance = (SensorValue[rightEncoder]/36000);

//---Turn---//:Turns robot to a given angle at a given speed.
void turn(int distance, int speed, bool direction, int brake, int wait)
{
	clearEncoders();
	if(direction == 0)
	{
		while(SensorValue[rightEncoder] <= distance)
		{
			base((-speed),(speed));
		}
		if(brake != 0)
		{
			base(-direction * brake,direction * brake);
			wait1Msec(100);
		}
		base(0,0);
		wait1Msec(wait);
	}
	else
	{
		while(leftDistance >= -distance || rightDistance >= -distance)
		{
			base((speed),(-speed));
		}
		if(brake != 0)
		{
			base(-direction * brake,direction * brake);
			wait1Msec(100);
		}
		base(0,0);
		wait1Msec(wait);
	}

}



//---Swing---//:Turns using only one side of the base.
void swing(int distance, int speed, int direction, int brake, int wait)
{
	clearEncoders();
	if(direction > 0)
	{
		while(direction * rightDistance < distance)
		{
			base(direction * speed,-10);
		}
		if(brake != 0)
		{
			base(-brake,0);
			wait1Msec(200);
		}
	}
	else
	{
		while(direction * leftDistance < distance)
		{
			base(-10,-direction * speed);
		}
		if(brake != 0)
		{
			base(0,-brake);
			wait1Msec(200);
		}
	}

	base(0,0);
	wait1Msec(wait);
}

void swingB(int distance, int speed, int direction, int brake, int wait)
{
	clearEncoders();
	if(direction > 0)
	{
		while(direction * leftDistance < distance)
		{
			base(10,-direction * speed);
		}
		if(brake != 0)
		{
			base(0,brake);
			wait1Msec(200);
		}
	}
	else
	{
		while(direction * rightDistance <distance)
		{
			base(direction * speed,10);
		}
		if(brake != 0)
		{
			base(brake,0);
			wait1Msec(200);
		}
	}

	base(0,0);
	wait1Msec(wait);
}

//---Forwards/Backwards---//:Moves the base forward and backward using IME's.
void fwds(int distance, int speed, int brake, int wait, int timer)
{
	clearTimer(T2);
	clearEncoders();
	while(abs(SensorValue[rightEncoder]) < distance && time1[T2] < timer)
	{
		base(speed,speed);
	}
	if(brake != 0)
	{
		base(-brake,-brake);
		wait1Msec(100);
	}
	base(0,0);
	wait1Msec(wait);
}

void bwds(int distance, int speed, int brake, int wait, int timer)
{
	fwds(distance, -speed, brake, wait, timer);
}

void bwdsT(int time, int speed, int wait)
{
	base(-speed,-speed);
	wait1Msec(time);
	base(0,0);
	wait1Msec(wait);
}

void fwdsT(int time, int speed, int wait)
{
	bwdsT(time,-speed,wait);
}

void stopBase()
{
	leftBase(0);
	rightBase(0);
}

void tipWarning()
{

	while(SensorValue[gyro] <= -70 && SensorValue[liftPot] > 2200)
	{
		playSound(soundBeepBeep);
		wait1Msec(100);
		base(127, 127);
		liftControl(-127);
		if(vexRT[Btn7R] == 1)
		{
			SensorValue[gyro] = 0;
		}
	}

	while(SensorValue[gyro] >= 80 && SensorValue[liftPot] > 2300)
	{
		playSound(soundBeepBeep);
		wait1Msec(100);
		base(-127, -127);
		liftControl(-127);
		if(vexRT[Btn7R] == 1)
		{
			SensorValue[gyro] = 0;
		}
	}

	if(time1[T1] >= 5000)
	{
		SensorValue[gyro] = 0;
		clearTimer(T1);
	}
	if(vexRT[Btn7R] == 1)
	{
		SensorValue[gyro] = 0;
	}
}


/*-------------------------------------------------------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------Pre-Autonomous Functions----------------------------------------------------------*/
/*-------------------------------------------------------------------------------------------------------------------------------------------*/
void pre_auton()
{

}
/*-------------------------------------------------------------------------------------------------------------------------------------------*/
/*                                                                                                                                           */
/*                                                              Autonomous Task                                                              */
/*                                                                                                                                           */
/*-------------------------------------------------------------------------------------------------------------------------------------------*/

task autonomous()
{
	if(autonNum == 0) //RED POLE
	{
		fwds(200, 80, 10, 500, 3000); //fwds(int distance, int speed, int brake, int wait, int timer);

		bwds(80, 70, 10, 500, 3000);
		while(SensorValue[clawPot] <= 2800)
		{
			motor[claw] = -127;
		}
		while(SensorValue[clawPot] >= 2500)
		{
			motor[claw] = 100;
		}
		motor[claw] = 0;
		fwds(200, 80, 10, 500, 3000);
		liftControl(-50);
		while(SensorValue[clawPot] <= 2800)
		{
			motor[claw] = -127;
		}
		liftControl(15);
		motor[claw] = -20;
		bwds(80, 80, 10, 500, 3000);
		while(SensorValue[liftPot] <= 2000)
		{
			liftControl(127);
		}
		liftControl(15);
		fwds(350, 70, 10, 500, 3000);
		while(SensorValue[liftPot] >= 1900)
		{
			liftControl(-80);
		}
		liftControl(15);
		while(SensorValue[clawPot] >= 2600)
		{
			motor[claw] = 100;
		}
		motor[claw] = 0;
		bwds(80, 80, 10, 500, 3000);
		wait1Msec(100);
		clearEncoders();
		while(abs(SensorValue[rightEncoder]) <= 50)
		{
			base(80,-80);
		}
		base(0,0);
		bwds(200, 80, 10, 400, 3000);
		wait1Msec(100);
		clearEncoders();
		wait1Msec(300);
		while(abs(SensorValue[rightEncoder]) <= 140)
		{
			base(-70,65);
		}
		base(10,-10);

	}
	else if(autonNum == 1)
	{
		fwds(100, 80, 10, 500, 3000);
		while(SensorValue[clawPot] <= 2800)
		{
			motor[claw] = -127;
		}
		while(SensorValue[clawPot] >= 2500)
		{
			motor[claw] = 100;
		}
		motor[claw] = 0;
		fwds(1100, 90, 10, 500, 3000);
		while(SensorValue[clawPot] <= 2600)
		{
			motor[claw] = -127;
		}
		motor[claw] = -40;
		while(SensorValue[liftPot] <= 1300)
		{
			liftControl(127);
		}
		liftControl(40);
		bwds(800, 80, 10, 400, 3000);
		clearEncoders();
		while(abs(SensorValue[rightEncoder]) <= 500)
		{
			base(80,-80);
		}
		base(0,0);
		fwds(250, 90, 10, 500, 3000);
		clearEncoders();
		while(abs(SensorValue[rightEncoder]) <= 150)
		{
			base(80,-80);
		}
		base(0,0);
		fwds(150, 90, 10, 500, 3000);
		while(SensorValue[clawPot] > 2500)
		{
			motor[claw] = 127;
		}
		motor[claw] = 0;
		fwds(50, 100, 10, 500, 3000);
		liftControl(15);
		bwds(150, 80, 10, 400, 3000);
	}
	else if(autonNum == 2)
	{

		fwds(100, 80, 10, 500, 3000);
		playSound(soundUpwardTones);
		while(SensorValue[clawPot] <= 2800)
		{
			motor[claw] = -127;
		}
		while(SensorValue[clawPot] >= 2500)
		{
			motor[claw] = 100;
		}
		motor[claw] = 0;
		fwds(1100, 90, 10, 500, 3000);
		while(SensorValue[clawPot] <= 2600)
		{
			motor[claw] = -127;
		}
		motor[claw] = -40;
		while(SensorValue[liftPot] <= 1300)
		{
			liftControl(127);
		}
		liftControl(40);
		bwds(800, 80, 10, 400, 3000);
		clearEncoders();
		while(abs(SensorValue[rightEncoder]) <= 400)
		{
			base(80,-80);
		}
		base(0,0);
		fwds(300, 90, 10, 500, 3000);
		clearEncoders();
		while(abs(SensorValue[rightEncoder]) <= 200)
		{
			base(80,-80);
		}
		base(0,0);
		fwds(200, 100, 10, 500, 3000);

		bwds(150, 80, 10, 400, 3000);
		wait1Msec(500);
		fwds(700, 127, 10, 500, 3000);

		while(SensorValue[clawPot] > 2500)
		{
			motor[claw] = 127;
		}
		motor[claw] = 0;
		bwds(200, 100, 10, 400, 3000);

		liftControl(15);
		clearEncoders();
		while(abs(SensorValue[rightEncoder]) <= 250)
		{
			base(80,-80);
		}
		base(0,0);
		while(SensorValue[clawPot] <= 2800)
		{
			motor[claw] = -127;
		}
		motor[claw] = 0;
		fwds(300, 127, 10, 500, 3000);
		playSound(soundDownwardTones);
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task usercontrol()
{
	bLCDBacklight = false;
	clearLCD();
	SensorValue[gyro] = 0;
	clearTimer(T1);
	while (true)
	{
		base(0,0,0,0); //base(bool setting, int speed, int duration,int side);
		lift(127, -80, 15); //lift(int upSpeed, int downSpeed, int hold);
		clawMove(127, -127, -10);
		autoLift(90, 50, 1450,10, 3000);
		LCDRun();
		tipWarning();
		leftDistance = (SensorValue[leftEncoder]/3600);
		rightDistance = (SensorValue[rightEncoder]/3600);
	}
}
