#pragma config(Sensor, in1,    baseGyro,       sensorGyro)
#pragma config(Sensor, in3,    mogoPot,        sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in5,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in6,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, in7,    vbPot,          sensorPotentiometer)
#pragma config(Sensor, in8,    navPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  towerPing,      sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl12, button,         sensorTouch)
#pragma config(Motor,  port1,           intake,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           rightFrontBase, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftFrontBase, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftBackBase,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightBackBase, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mobile,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          elevator,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void Kill()//Kills power
{
	motor[intake] = 0;
	motor[rightFrontBase] = 0;
	motor[leftFrontBase] = 0;
	motor[rightLift] = 0;
	motor[leftLift] = 0;
	motor[leftBackBase] = 0;
	motor[rightBackBase] = 0;
	motor[mobile] = 0;
	motor[elevator] = 0;
}

//-----MOTOR_CONNECTION_FUNCTIONS-----//
void leftBase(int power)//Function used to control all the motors on the left side of the base at once.
{
	motor[leftFrontBase] = power;
	motor[leftBackBase] = power;
}

void rightBase(int power)//Function used to control all the motors on the right side of the base at once.
{
	motor[rightFrontBase] = power;
	motor[rightBackBase] = power;
}

void baseDriver(int leftSpeed, int rightSpeed)//Function to control base during driver control
{
	leftBase(leftSpeed);
	rightBase(rightSpeed);
}
void base(int rSpeed, int lSpeed){
	baseDriver(lSpeed, rSpeed);}

void liftControl(int power)//Function used to control all the motors on the lift at once.
{
	motor[rightLift] = power;
	motor[leftLift] = power;
}

void clearEncoders()
{
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
}

void autonRun();
/*-------------------------------------------------------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------Pre-Autonomous Functions----------------------------------------------------------*/
/*-------------------------------------------------------------------------------------------------------------------------------------------*/
void pre_auton()
{
	SensorValue[gyro] = 0;
	SensorValue[baseGyro] = 0;
	clearEncoders();
	clearTimer(T1);
}
/*-------------------------------------------------------------------------------------------------------------------------------------------*/
/*                                                                                                                                           */
/*                                                              Autonomous Task                                                              */
/*                                                                                                                                           */
/*-------------------------------------------------------------------------------------------------------------------------------------------*/
task autonomous()
{}
/////////////////////////////////////////////////////////////////////////////////

void clawMove(int openSpeed, int closeSpeed, int hold)//try using sometime
{

	if(vexRT[Btn7U] == vexRT[Btn6U])
	{
		motor[intake] = hold;
	}
	else if(vexRT[Btn7U] == 1 && SensorValue[clawPot] >= 2400)
	{
		motor[intake] = openSpeed;
	}
	else if(vexRT[Btn7D] == 1  && SensorValue[clawPot] <= 3000)
	{
		clearTimer(T3);
		if(time1[T3] < 1000)
		{
			motor[intake] = closeSpeed;
		}
	}
	else
	{
		motor[intake] = (hold - 10);
	}
}

int liftVal;
void liftUserControl(int speed, int hold)
{
	if(vexRT[Btn5U] == 1)
	{
		liftControl(speed);
	}
	else if(vexRT[Btn5D] == 1)
	{
		liftControl(-speed);
	}
	else if(vexRT[Btn6U] == 1 || vexRT[Btn6D] == 1)
	{

	}
	else if(vexRT[Btn7L] == 1)
	{
		while(SensorValue[liftPot] <= 1350)
		{
			liftControl(-speed);
		}
		while(SensorValue[liftPot] >= 1350)
		{
			liftControl(speed);
		}
		liftControl(hold);
	}

	else if(vexRT[Btn7R] == 1)
	{
		//clawClose(3100, -127, -10);//(potValue, speed, hold)
		clearTimer(T3);
		while(SensorValue[towerPing] <= 20 && SensorValue[liftPot] >= 5 && time1[T3] < 5000 && vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0)
		{
			liftControl(110);
		}
		liftVal = SensorValue[liftPot];
		liftControl(hold+20);
		clearTimer(T3);
		while(SensorValue[vbPot] >= 400 && time1[T3] < 2000 && vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0)
		{
			motor[elevator] = 127;
		}
		motor[elevator] = 30;
		wait1Msec(150);
		clearTimer(T3);
		while(SensorValue[liftPot] <= (liftVal+150) && time1[T3] < 2000 && vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0)
		{
			liftControl(-60);
		}
		liftControl(hold+30);
		wait1Msec(150);
		//clawOpen(2575, -127, -15);//(potValue, speed, hold)
		wait1Msec(100);
		clearTimer(T3);
		while(SensorValue[liftPot] >= (liftVal-200) && time1[T3] < 2000 && vexRT[Btn7U] == 0 && vexRT[Btn7D] == 0)
		{
			liftControl(110);
		}
		liftControl(hold);
		wait1Msec(200);
		clearTimer(T3);
		while(SensorValue[vbPot] <= 1400 && time1[T3] < 2000 && vexRT[Btn7U] == 0 && vexRT[Btn7D] == 0)
		{
			motor[elevator] = -127;
		}
		motor[elevator] = 20;
		wait1Msec(50);
		clearTimer(T3);
		while(SensorValue[liftPot] <= 1350 && time1[T3] < 2000 && vexRT[Btn7U] == 0 && vexRT[Btn7D] == 0)
		{
			liftControl(-90);
		}
		liftControl(hold+10);
	}
	else
	{
		if(SensorValue[liftPot] >= 1500)
		{
			liftControl(0);
		}
		else
		{
			liftControl(hold);
		}
	}
}


void vbUserControl(int speed, int hold)
{
		if(vexRT[Btn8D] == 1)
		{
			motor[elevator] = -speed;
		}
		else if(vexRT[Btn8U] == 1)
		{
			motor[elevator] = speed;
		}
		else if(vexRT[Btn8R]) //DOWN
		{
			int timer = 2000;
			clearTimer(T3);
			if(SensorValue[vbPot] <= 350 || SensorValue[vbPot] <= 1400)
			{
				while(SensorValue[vbPot] <= 1400 && time1[T3] < timer)
				{
					motor[elevator] = -speed;
				}
				motor[elevator] = hold;
			}
			else if(SensorValue[vbPot] <= 1400 || SensorValue[vbPot] <= 2550)
			{

				while(SensorValue[vbPot] <= 2550 && time1[T3] < timer)
				{
					motor[elevator] = -speed;
				}
				motor[elevator] = hold;
			}
			else
			{
				motor[elevator] = hold;
			}
		}
		else if(vexRT[Btn8L])//UP
		{
			int timer = 1000;
			clearTimer(T3);
			if(SensorValue[vbPot] >= 2600 || SensorValue[vbPot] >= 2000)
			{
				while(SensorValue[vbPot] >= 2000 && time1[T3] < timer)
				{
					motor[elevator] = speed;
				}
				motor[elevator] = hold;
			}
			else if(SensorValue[vbPot] >= 2000 || SensorValue[vbPot] >= 350)
			{
				while(SensorValue[vbPot] >= 400 && time1[T3] < timer)
				{
					motor[elevator] = speed;
				}
				motor[elevator] = hold;
			}
			else
			{
				motor[elevator] = hold;
			}
		}
		else
		{
			motor[elevator] = hold;
		}
}

void mobileGoal()//Function used to control all the motors on the lift at once.
{
	if (vexRT[Btn6U] == 1)
	{
		if(SensorValue[liftPot] >= 1300)
		{
			liftControl(127);
		}
		else
		{
			liftControl(15);
			motor[mobile] = 127;
		}
	}
	else if(vexRT[Btn6D] == 1)
	{
		if(SensorValue[liftPot] >= 1300)
		{
			liftControl(127);
		}
		else
		{
			liftControl(15);
			motor[mobile] = -127;
		}
	}
	else
	{
		motor[mobile] = 0;
	}
}

void intakeClaw(int speed, int hold)
{
	if(vexRT[Btn7U] == 1 && vexRT[Btn7D] == 1)
	{
		motor[intake] = 0;
	}
	else if(vexRT[Btn7D] == 1)
	{
		motor[intake] = speed;
	}
	else if(vexRT[Btn7U] == 1)
	{
		motor[intake] = -speed;
	}
	else
	{
		if(SensorValue[clawPot] <= 3100)
		{
			motor[intake] = 0;
		}
		else
		{
			motor[intake] = hold;
		}
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*---------------------------------------------------------------------------*/
task usercontrol()
{
	bLCDBacklight = false;
	SensorValue[gyro] = 0;
	clearEncoders();
	clearTimer(T1);
	while (true)
	{
		baseDriver(vexRT[Ch3], vexRT[Ch2]);
		mobileGoal();
		intakeClaw(127, 10);
		liftUserControl(127, 15);
		vbUserControl(127, 15);
	}
}
