#pragma config(Sensor, in2,    baseGyro,       sensorGyro)
#pragma config(Sensor, in3,    ballDetectorBottom, sensorLineFollower)
#pragma config(Sensor, in4,    turnerSensor,   sensorPotentiometer)
#pragma config(Sensor, in5,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, in6,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in7,    ballDetectorTop, sensorLineFollower)
#pragma config(Sensor, dgtl1,  leftBaseEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  turnerTop,      sensorTouch)
#pragma config(Sensor, dgtl9,  flyWheelEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, rightBaseEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           capClaw,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           flyWheel,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           ballIntake,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           leftFrontBase, tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           rightFrontBase, tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           rightMiddleBase, tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port7,           leftMiddleBase, tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           lift,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           capTurner,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          ballElevator,  tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#pragma DebuggerWindows("Globals")
#pragma DebuggerWindows("Motors")

float showError = 0;
#include "functions/buttonDefinitions.h"
#include "functions/sensorDefinitions.h"
#include "functions/motorControlFunctions.h"
#include "functions/driverControl.h"
#include "functions/autonomusFunctions.h"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



task autonomous()
{
	shootingSpeed = 48;
	revUp = on;
	startTask(autoFlyWheel);

	SensorType[in2] = sensorGyro;
 	wait1Msec(1150);


	startTask(autoBallIntake);
	drivePID(forwards, 46);

	drivePID(backwards, 36.5);
	stopTask(autoBallIntake);
	driveTurnPID(right, 90);

	drivePID(forwards, 13);
	pew();
	drivePID(forwards, 15.5);
	pew();
	revUp = off;
	wait1Msec(500);
	driveTurnPID(right, 12);
	drivePID(forwards, 15);
	driveTurnPID(left, 12);
	drivePID(forwards, 17);
	stopTask(autoFlyWheel);
	drivePID(backwards, 24);

/*
	shootingSpeed = 33.5;
	revUp = on;
	startTask(autoFlyWheel);

	pew();
	wait1Msec(500);
	pew();
	revUp = off;
	stopTask(autoFlyWheel);
	driveTurnPID(right, 3);
	ballIntakeMotor(100);
  ballElevatorMotor(100);
	drivePID(forwards, 46);
	ballIntakeMotor(0);
  ballElevatorMotor(0);
*/

	/* // front tile top flag
	shootingSpeed = 41;
	revUp = on;
	startTask(autoFlyWheel);

	pew();
	wait1Msec(500);
	pew();
	revUp = off;
	stopTask(autoFlyWheel);
	*/
	while(true)
	{
		stopTask(autoFlyWheel);
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop
	clearTimer(T2);
	while (true)
	{
		directionController(changeDirectionBtn);
		baseController(Y_rightJoy, Y_leftJoy);
		liftControl(liftUpBtn, liftDownBtn, liftSensor);
		ballIntakeController(currentIntake(1), currentOuttake(1));
		capIntakeController(currentIntake(0), currentOuttake(0), clawSensor);
		capRotateController(capRotateBtn,clawTurnerSensor); //clawTurnerSensor
		flyWheelController(flyWheelToggleBtn, 48);
		//Cross Cort -- 53
		//Aginst Back Tile -- Top Flag -- 48
		//One Tile Up -- Top Flag -- 46.5
		//Front colored tile -- Top Flag -- 40
		//Front colored tile -- Top Flag -- 33

	}
}
