#pragma config(Sensor, in1,    tipGyro,        sensorGyro)
#pragma config(Sensor, in2,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    turnerPot,      sensorPotentiometer)
#pragma config(Sensor, in4,    ballDetectorTop, sensorLineFollower)
#pragma config(Sensor, in5,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in6,    ballDetectorBottom, sensorLineFollower)
#pragma config(Sensor, dgtl1,  flyWheelEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftBaseEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightBaseEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           capClaw,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           flyWheel,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           leftFrontBase, tmotorVex393TurboSpeed_MC29, PIDControl, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port5,           rightFrontBase, tmotorVex393TurboSpeed_MC29, PIDControl, driveRight, encoderPort, dgtl5)
#pragma config(Motor,  port6,           rightMiddleBase, tmotorVex393TurboSpeed_MC29, PIDControl, driveRight, encoderPort, dgtl5)
#pragma config(Motor,  port7,           leftMiddleBase, tmotorVex393TurboSpeed_MC29, PIDControl, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port8,           lift,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           capTurner,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          ballIntake,    tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "functions/buttonDefinitions.h"
#include "functions/sensorDefinitions.h"
#include "functions/motorControlFunctions.h"
#include "functions/driverControl.h"
#include "functions/autonomusFunctions.h"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



task autonomous()
{
	driveTime(right, 127, 2000, true);//driveTime(direction?,speed,time,stopWithBreaks?,breakSpeed,breakTime)
	driveTime(forwards, 127, 2000, true);//driveTime(direction?,speed,time,stopWithBreaks?,breakSpeed,breakTime)
	driveSensor(forwards, 127, 100, true, 3000);//driveSensor(direction?,speed,measurement,useBreaks,timer)
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		directionController(changeDirectionBtn);
		baseController(Y_rightJoy, Y_leftJoy);
		liftControl(liftUpBtn, liftDownBtn, liftSensor);
		ballIntakeController(currentIntake(1), currentOuttake(1));
		capIntakeController(currentIntake(0), currentOuttake(0));
		capRotateController(capRotateCWBtn, capRotateCCWBtn);
		flyWheelController(flyWheelToggleBtn);
	}
}
