#pragma config(Sensor, in3,    navPot,         sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in5,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in6,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  towerPing,      sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMiddle,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftOne,       tmotorNone, openLoop)
#pragma config(Motor,  port6,           liftTwo,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightMiddle,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightBack,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
bool LCDState = false;
string mainBattery, backupBattery;


//Default AUTON Number//
// RED  POLE     == 0 //
// RED  RIGHT1   == 1 //
// RED  LEFT1    == 2 //
// Defence     == 3 //
// BLUE RIGHT1   == 4 //
// BLUE LEFT1    == 5 //
// SKILLS        == 6 //
// BLUE RIGHT2   == 7  v         //
// RED  RIGHT2   == 8 //
// BLUE LEFT2    == 9 //
// RED  LEFT2    == 10//
int autonNum = 0;
//Default AUTON Number//


//----------LCD-----------//
//                        //7
//       Left = ON        //
//     Center = Select    //
//      Right = OFF       //
//                        //
// Pot = Switch Selection //
//                        //
//------------------------//

//Variables
int stateCheck = 0;
int soundCheck = 0;

void clearLCD()//Clear both LCD lines
{
	clearLCDLine(0);
	clearLCDLine(1);
}

void clearSound(int time)//Stop playing sounds after (int time) seconds
{
	wait1Msec(time);
	clearSounds();
}

void testSound()//Sound function for determining if blip sound was played while using LCD
{
	if(stateCheck != soundCheck)//If sound was not played then play sound
	{
		playSound(soundShortBlip);
		soundCheck = stateCheck;
	}
	else//No sound if sound was already played
	{
		wait1Msec(100);
		clearSounds();
	}
}

void LCDRun()//Main LCD function
{
	if(nLCDButtons == leftButton)//Turns on the LCD
	{
		LCDState = true;
		playSound(soundUpwardTones);
		bLCDBacklight = true;
		clearSound(500);
	}
	if(LCDState == true)
	{
		if(SensorValue[navPot] <= 500)//RED POLE == 0
		{
			testSound();
			stateCheck = 0;
			displayLCDCenteredString(0,"==              ");
			displayLCDCenteredString(1,"    RED POLE   >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 0;
				displayLCDCenteredString(0,"----RED POLE----");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound(500);
				wait1Msec(1500);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound(500);
			}
		}
		else if(SensorValue[navPot] >= 500 && SensorValue[navPot] <= 1000)//RED RIGHT == 1
		{
			testSound();
			stateCheck = 1;
			displayLCDCenteredString(0,"  ==            ");
			displayLCDCenteredString(1,"<  RED  RIGHT  >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 1;
				displayLCDCenteredString(0,"---RED  RIGHT---");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound(500);
				wait1Msec(1500);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound(500);
			}
		}
		else if(SensorValue[navPot] >= 1000 && SensorValue[navPot] <= 1500)//RED LEFT == 2
		{
			stateCheck = 2;
			testSound();
			displayLCDCenteredString(0,"    ==          ");
			displayLCDCenteredString(1,"<   RED LEFT   >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 2;
				displayLCDCenteredString(0,"----RED LEFT----");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound(500);
				wait1Msec(1500);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound(500);
			}
		}
		else if(SensorValue[navPot] >= 1500 && SensorValue[navPot] <= 2000)//BLUE POLE == 3
		{
			stateCheck = 3;
			testSound();
			displayLCDCenteredString(0,"      ==        ");
			displayLCDCenteredString(1,"<  BLUE  POLE  >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 3;
				displayLCDCenteredString(0,"---BLUE  POLE---");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound(500);
				wait1Msec(1500);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound(500);
			}
		}
		else if(SensorValue[navPot] >= 2000 && SensorValue[navPot] <= 2500)//BLUE RIGHT == 4
		{
			stateCheck = 4;
			testSound();
			displayLCDCenteredString(0,"        ==      ");
			displayLCDCenteredString(1,"<  BLUE RIGHT  >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 4;
				displayLCDCenteredString(0,"---BLUE RIGHT---");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound(500);
				wait1Msec(2000);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound(500);
			}
		}
		else if(SensorValue[navPot] >= 2500 && SensorValue[navPot] <= 3000)//BLUE LEFT == 5
		{
			stateCheck = 5;
			testSound();
			displayLCDCenteredString(0,"          ==    ");
			displayLCDCenteredString(1,"<  BLUE  LEFT  >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 5;
				displayLCDCenteredString(0,"---BLUE  LEFT---");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound(500);
				wait1Msec(2000);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound(500);
			}
		}
		else if(SensorValue[navPot] >= 3000 && SensorValue[navPot] <= 3500)//SKILLS == 6
		{
			stateCheck = 6;
			testSound();
			displayLCDCenteredString(0,"            ==  ");
			displayLCDCenteredString(1,"<    SKILLS    >");
			if(nLCDButtons == centerButton)
			{
				autonNum = 6;
				displayLCDCenteredString(0,"-----SKILLS-----");
				displayLCDCenteredString(1,"   *SELECTED*   ");
				playSound(soundException);
				clearSound(500);
				wait1Msec(2000);
				LCDState = false;
				playSound(soundDownwardTones);
				clearSound(500);
			}
		}
		else//Check Battery Voltage
		{
			stateCheck = 7;
			testSound();
			displayLCDCenteredString(0,"              ==");
			displayLCDCenteredString(1,"<    BATTERY    ");
			while(nLCDButtons == centerButton)
			{
				displayLCDString(0,0,"  Primary: ");
				sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
				displayNextLCDString(mainBattery);
				displayLCDCenteredString(1," ");
			}

		}
		if(nLCDButtons == rightButton)
		{
			LCDState = false;
			playSound(soundDownwardTones);
			wait1Msec(500);
			clearSounds();
		}
	}
	else
	{
		clearLCD();
		bLCDBacklight = false;
	}
}

//------------------------//
//                        //
//       Left = ON        //
//     Center = Select    //
//      Right = OFF       //
//                        //
// Pot = Switch Selection //
//                        //
//----------LCD-----------//




//********************************************************************************************************//
//********************************************DRIVER_FUNCTIONS*********************************************//
//********************************************************************************************************//


//-----MOTOR_CONNECTION_FUNCTIONS-----//
void leftBase(int power)//Function used to control all the motors on the left side of the base at once.
{
	motor[leftFront] = power;
	motor[leftMiddle] = power;
	motor[leftBack] = power;
}

void rightBase(int power)//Function used to control all the motors on the right side of the base at once.
{
	motor[rightFront] = power;
	motor[rightMiddle] = power;
	motor[rightBack] = power;
}

void liftControl(int power)//Function used to control all the motors on the lift at once.
{
	motor[liftOne] = power;
	motor[liftTwo] = power;
}
//-----MOTOR_CONNECTION_FUNCTIONS-----//


void baseDriver(int leftSpeed, int rightSpeed)//Function to control base during driver control
{
	leftBase(leftSpeed);
	rightBase(rightSpeed);
}

int mobilePickup = 0;
void lift(int upSpeed, int downSpeed, int hold,  int upSpeedAuto, int distance, int height, int timer)
{
	clearTimer(T2);
	if(vexRT[Btn5U] == 1)
	{
		liftControl(upSpeed);
		mobilePickup = 0;
	}
	else if(vexRT[Btn5D] == 1)
	{
		liftControl(downSpeed);
		mobilePickup = 0;
	}
	else if(vexRT[Btn7U] == 1)
	{
		liftControl(upSpeed);
		mobilePickup = 1;
	}
	else if(vexRT[Btn7D] == 1)
	{
		liftControl(downSpeed+40);
		mobilePickup = 1;
	}
	else if(vexRT[Btn8R] == 1)
	{
		while(SensorValue[towerPing] <= distance && time1[T2] < timer)
		{
			liftControl(upSpeedAuto);
		}
	}
	else if(vexRT[Btn8L] == 1)
	{
		while(SensorValue[liftPot] <= height && time1[T2] < timer)
		{
			liftControl(upSpeedAuto);
		}
		while(SensorValue[liftPot] >= (height+300) && time1[T2] < timer)
		{
			liftControl(-upSpeedAuto);
		}
	}
	else
	{
		if(SensorValue[liftPot] <= 1400 && mobilePickup == 0)
		{
			liftControl(hold-10);
		}
		else if(mobilePickup == 1)
		{
			liftControl(hold+15);
		}
		else
		{
			liftControl(hold);
		}
	}
}

void clawMove(int openSpeed, int closeSpeed, int hold)
{

		if(vexRT[Btn6U] == vexRT[Btn6D])
		{
			motor[claw] = hold;
		}
		else if(vexRT[Btn6U] == 1 && SensorValue[clawPot] >= 2400)
		{
			motor[claw] = openSpeed;
		}
		else if(vexRT[Btn6D] == 1  && SensorValue[clawPot] <= 3000)
		{
			clearTimer(T3);
			if(time1[T3] < 1000)
			{
				motor[claw] = closeSpeed;
			}
		}
		else
		{
			motor[claw] = (hold - 10);
		}

}

void base(int rSpeed, int lSpeed)
{
	rightBase(rSpeed);
	leftBase(lSpeed);
}

void tipWarning()
{

	while(SensorValue[gyro] <= -70 && SensorValue[liftPot] > 2200)
	{
		playSound(soundBeepBeep);
		wait1Msec(100);
		base(127, 127);
		liftControl(-127);
		if(vexRT[Btn7R] == 1)
		{
			SensorValue[gyro] = 0;
		}
	}

	while(SensorValue[gyro] >= 80 && SensorValue[liftPot] > 2300)
	{
		playSound(soundBeepBeep);
		wait1Msec(100);
		base(-127, -127);
		liftControl(-127);
		if(vexRT[Btn7R] == 1)
		{
			SensorValue[gyro] = 0;
		}
	}

	if(time1[T1] >= 5000)
	{
		SensorValue[gyro] = 0;
		clearTimer(T1);
	}
	if(vexRT[Btn7R] == 1)
	{
		SensorValue[gyro] = 0;
	}
}


//********************************************************************************************************//
//********************************************AUTON_FUNCTIONS*********************************************//
//********************************************************************************************************//

void clearEncoders()
{
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
}



void fwds(int distance, int speed, int brake, int wait, int timer)
{
	clearTimer(T2);
	clearEncoders();
	while(abs(SensorValue[rightEncoder]) < distance && time1[T2] < timer)
	{
		base(speed,speed);
	}
	if(brake != 0)
	{
		base(-brake,-brake);
		wait1Msec(100);
	}
	base(0,0);
	wait1Msec(wait);
}

void bwds(int distance, int speed, int brake, int wait, int timer)
{
	fwds(distance, -speed, brake, wait, timer);
}

void bwdsT(int time, int speed, int wait)
{
	base(-speed,-speed);
	wait1Msec(time);
	base(0,0);
	wait1Msec(wait);
}

void fwdsT(int time, int speed, int wait)
{
	bwdsT(time,-speed,wait);
}

void turnRight(int distance, int speed, int brake, int wait)
{
	clearEncoders();
	//RIGHT
		while(abs(SensorValue[rightEncoder]) <= distance)
		{
			base((-speed),(speed));
		}
		if(brake != 0)
		{
			base(brake,-brake);
			wait1Msec(100);
		}
		base(0,0);
		wait1Msec(wait);
}

void turnLeft(int distance, int speed, int brake, int wait)
{
	clearEncoders();
	//LEFT
		while(abs(SensorValue[rightEncoder]) <= distance)
		{
			base((speed),(-speed));
		}
		if(brake != 0)
		{
			base(-brake,brake);
			wait1Msec(100);
		}
		base(0,0);
		wait1Msec(wait);
}

void clawOpen(int potValue, int speed, int hold)
{
	while(SensorValue[clawPot] >= potValue)
	{
		motor[claw] = speed;
	}
	motor[claw] = hold;
}

void clawClose(int potValue, int speed, int hold)
{
	while(SensorValue[clawPot] <= potValue)
	{
		motor[claw] = -speed;
	}
	motor[claw] = -hold;
}

void liftUp(int potValue, int speed, int hold, int wait, int timer)
{
	clearTimer(T2);
	while(SensorValue[liftPot] <= potValue && time1[T2] < timer)
	{
		liftControl(speed);
	}
	liftControl(hold);
	wait1Msec(wait);
}

void liftDown(int potValue, int speed, int hold, int wait, int timer)
{
	clearTimer(T2);
	while(SensorValue[liftPot] >= potValue && time1[T2] < timer)
	{
		liftControl(-speed);
	}
	liftControl(-hold);
	wait1Msec(wait);
}

void autonRun();
/*-------------------------------------------------------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------Pre-Autonomous Functions----------------------------------------------------------*/
/*-------------------------------------------------------------------------------------------------------------------------------------------*/
void pre_auton()
{
	clearLCD();
	SensorValue[gyro] = 0;
	clearEncoders();
	clearTimer(T1);
	LCDRun();
}
/*-------------------------------------------------------------------------------------------------------------------------------------------*/
/*                                                                                                                                           */
/*                                                              Autonomous Task                                                              */
/*                                                                                                                                           */
/*-------------------------------------------------------------------------------------------------------------------------------------------*/


// RED  POLE     == 0 //
// RED  RIGHT1   == 1 //
// RED  LEFT1    == 2 //
// BLUE POLE     == 3 //
// BLUE RIGHT1   == 4 //
// BLUE LEFT1    == 5 //
// SKILLS        == 6 //
// BLUE RIGHT2   == 7 //
// RED  RIGHT2   == 8 //
// BLUE LEFT2    == 9 //
// RED  LEFT2    == 10//

task autonomous()
{
	autonRun();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*---------------------------------------------------------------------------*/
task usercontrol()
{
	bLCDBacklight = false;
	clearLCD();
	SensorValue[gyro] = 0;
	clearEncoders();
	clearTimer(T1);
	while (true)
	{
		baseDriver(vexRT[Ch3], vexRT[Ch2]); //void base(int leftSpeed, int rightSpeed); //Function to control base during driver control
		lift(127, -80, 15, 90, 50, 1450, 3000); //void lift(int upSpeed, int downSpeed, int hold,  int upSpeedAuto, int distance, int height, int timer);
		clawMove(127, -127, -10);
		LCDRun();
		tipWarning();
	}
}


void autonRun()
{
	if(autonNum == 0)//---RED_POLE---//
	{
		fwds(150, 80, 10, 250, 3000);//(distance, speed, brake, wait, timer)
		bwds(80, 70, 10, 250, 3000);//(distance, speed, brake, wait, timer)
		clawClose(3200, 80, 0);//(potValue, speed, hold)
		wait1Msec(200);
		clawOpen(2900, 100, 10);//(potValue, speed, hold)
		wait1Msec(200);
		fwds(180, 80, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftControl(-50);//(speed)
		wait1Msec(200);
		clawClose(3000, 127, 20);//(potValue, speed, hold)
		liftControl(15);//(speed)
		bwds(80, 80, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftUp(2000, 127, 15, 100, 3000);//(potValue, speed, hold, wait, timer)
		fwds(350, 70, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftDown(1900, 80, 15, 500, 3000);//(potValue, speed, hold, wait, timer)
		clawOpen(2600, 100, 0);//(potValue, speed, hold)
		bwds(80, 80, 10, 600, 3000);//(distance, speed, brake, wait, timer)
	}
	else if(autonNum == 1)//---RED_RIGHT_10_POINT---//
	{
		liftControl(10);//(speed)
		fwds(1300, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		bwds(100, 80, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnRight(90, 80, 10, 200);//(distance, speed, brake, wait)
		clawClose(3500, 100, 0);//(potValue, speed, hold)
		wait1Msec(500);
		clawOpen(2800, 100, 0);//(potValue, speed, hold)
		fwds(300, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftControl(-10);//(speed)
		clawClose(2900, 127, 40);//(potValue, speed, hold)
		liftUp(1400, 127, 40, 100, 3000);//(potValue, speed, hold, wait, timer)
		bwds(200, 80, 10, 250, 3000);//(distance, speed, brake, wait, timer)
		turnRight(600, 80, 10, 250);//(distance, speed, brake, wait)
		fwds(850, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(130, 80, 10, 100);//(distance, speed, brake, wait)
		fwds(200, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawOpen(2500, 127, 10);//(potValue, speed, hold)
		liftDown(1300, 127, 10, 200, 3000);//(potValue, speed, hold, wait, timer)
		fwds(100, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftUp(1400, 127, 15, 100, 3000);//(potValue, speed, hold, wait, timer)
		clawClose(3000, 127, 40);//(potValue, speed, hold)
		bwds(50, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnRight(75, 80, 10, 100);//(distance, speed, brake, wait)
		bwds(1100, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftDown(1220, 127, 10, 200, 3000);//(potValue, speed, hold, wait, timer)
		liftControl(0);//(speed)
	}
	else if(autonNum == 2)//---RED_LEFT_10_POINT---//
	{
		liftControl(10);//(speed)
		fwds(1300, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		bwds(100, 80, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(90, 80, 10, 200);//(distance, speed, brake, wait)
		clawClose(3500, 100, 0);//(potValue, speed, hold)
		wait1Msec(500);
		clawOpen(3000, 100, 0);//(potValue, speed, hold)
		fwds(300, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawClose(2900, 127, 40);//(potValue, speed, hold)
		liftUp(1400, 127, 40, 100, 2000);//(potValue, speed, hold, wait, timer)
		bwds(200, 80, 10, 250, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(500, 80, 10, 250);//(distance, speed, brake, wait)
		fwds(1000, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnRight(80, 80, 10, 100);//(distance, speed, brake, wait)
		fwds(150, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawOpen(2500, 127, 10);//(potValue, speed, hold)
		liftDown(1300, 127, 10, 200, 3000);//(potValue, speed, hold, wait, timer)
		fwds(100, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftUp(1400, 127, 15, 100, 3000);//(potValue, speed, hold, wait, timer)
		clawClose(3000, 127, 40);//(potValue, speed, hold)
		bwds(50, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(75, 80, 10, 100);//(distance, speed, brake, wait)
		bwds(900, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftDown(1220, 127, 10, 200, 3000);//(potValue, speed, hold, wait, timer)
		liftControl(0);//(speed)
	}
	else if(autonNum == 3)//---Defence---//
	{
		fwds(1800, 127, 10, 10, 3000);//(distance, speed, brake, wait, timer)
		bwds(150, 127, 10, 10, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(100, 80, 10, 10);//(distance, speed, brake, wait)
		fwds(800, 127, 10, 10, 3000);//(distance, speed, brake, wait, timer)
	}
	else if(autonNum == 4)//---BLUE_RIGHT_10_POINT---//
	{
		fwds(100, 80, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawClose(3100, 127, 0);//(potValue, speed, hold)
		clawOpen(2900, 100, 0);//(potValue, speed, hold)
		fwds(1100, 90, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawClose(2900, 127, 40);//(potValue, speed, hold)
		liftUp(1300, 127, 40, 100, 3000);//(potValue, speed, hold, wait, timer)
		bwds(800, 80, 10, 400, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(400, 80, 10, 100);//(distance, speed, brake, wait)
		fwds(250, 90, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(250, 80, 10, 100);//(distance, speed, brake, wait)
		fwds(250, 90, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawOpen(2500, 127, 0);//(potValue, speed, hold)
		fwds(50, 100, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftControl(15);//(speed)
		bwds(150, 80, 10, 400, 3000);//(distance, speed, brake, wait, timer)
	}
	else if(autonNum == 5)//---BLUE_LEFT_10_POINT---//
	{
		liftControl(10);//(speed)
		fwds(1300, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		bwds(100, 80, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(100, 80, 10, 200);//(distance, speed, brake, wait)
		clawClose(3500, 100, 0);//(potValue, speed, hold)
		wait1Msec(500);
		clawOpen(2800, 100, 0);//(potValue, speed, hold)
		fwds(300, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftControl(-10);//(speed)
		clawClose(2900, 127, 40);//(potValue, speed, hold)
		liftUp(1400, 127, 40, 100, 3000);//(potValue, speed, hold, wait, timer)
		bwds(200, 80, 10, 250, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(400, 80, 10, 250);//(distance, speed, brake, wait)
		fwds(1000, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnRight(75, 80, 10, 100);//(distance, speed, brake, wait)
		fwds(100, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawOpen(2500, 127, 10);//(potValue, speed, hold)
		liftDown(1300, 127, 10, 200, 3000);//(potValue, speed, hold, wait, timer)
		fwds(100, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftUp(1400, 127, 15, 100, 3000);//(potValue, speed, hold, wait, timer)
		clawClose(3000, 127, 40);//(potValue, speed, hold)
		bwds(50, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(75, 80, 10, 100);//(distance, speed, brake, wait)
		bwds(1100, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftDown(1220, 127, 10, 200, 3000);//(potValue, speed, hold, wait, timer)
		liftControl(0);//(speed)
	}
	else if(autonNum == 6)//---SKILLS---//
	{
		fwds(200, 80, 10, 250, 3000);//(distance, speed, brake, wait, timer)
		bwds(80, 70, 10, 250, 3000);//(distance, speed, brake, wait, timer)
		clawClose(3400, 100, 0);//(potValue, speed, hold)
		clawOpen(2900, 127, 0);//(potValue, speed, hold)
		fwds(200, 80, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftControl(-50);//(speed)
		clawClose(3300, 127, 20);//(potValue, speed, hold)
		liftControl(15);//(speed)
		bwds(80, 80, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftUp(1700, 127, 15, 100, 3000);//(potValue, speed, hold, wait, timer)
		fwds(625, 70, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftDown(1300, 80, 15, 500, 3000);//(potValue, speed, hold, wait, timer)
		clawOpen(2900, 100, 0);//(potValue, speed, hold)
		bwds(80, 80, 10, 600, 3000);//(distance, speed, brake, wait, timer)


	}
	else if(autonNum ==7) //---BLUE_RIGHT_20_POINT---//
	{
		fwds(100, 80, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawClose(3100, 127, 0);//(potValue, speed, hold)
		clawOpen(2900, 100, 0);//(potValue, speed, hold)
		fwds(1100, 90, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawClose(2900, 127, 40);//(potValue, speed, hold)
		liftUp(1300, 127, 40, 100, 3000);//(potValue, speed, hold, wait, timer)
		bwds(800, 80, 10, 400, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(400, 80, 10, 100);//(distance, speed, brake, wait)
		fwds(450, 90, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(300, 80, 10, 100);//(distance, speed, brake, wait)
		fwds(700, 90, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawOpen(2500, 127, 0);//(potValue, speed, hold)
		fwds(50, 100, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftControl(15);//(speed)
		bwds(400, 80, 10, 400, 3000);//(distance, speed, brake, wait, timer)
	}
	else if(autonNum ==8) //---RED_RIGHT_20_POINT---//
	{
		liftControl(10);//(speed)
		fwds(1300, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		bwds(100, 80, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnRight(90, 80, 10, 200);//(distance, speed, brake, wait)
		clawClose(3500, 100, 0);//(potValue, speed, hold)
		wait1Msec(500);
		clawOpen(2800, 100, 0);//(potValue, speed, hold)
		fwds(300, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawClose(3000, 127, 40);//(potValue, speed, hold)
		liftUp(1400, 127, 40, 100, 3000);//(potValue, speed, hold, wait, timer)
		bwds(200, 80, 10, 250, 3000);//(distance, speed, brake, wait, timer)
		turnRight(550, 80, 10, 250);//(distance, speed, brake, wait)
		fwds(1000, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnRight(60, 80, 10, 100);//(distance, speed, brake, wait)
		fwds(50, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(235, 80, 10, 100);//(distance, speed, brake, wait)
		fwds(100, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		bwds(150, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		fwds(700, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawOpen(2500, 127, 10);//(potValue, speed, hold)
		liftDown(1300, 127, 10, 200, 3000);//(potValue, speed, hold, wait, timer)
		fwds(50, 127, 10, 500, 1000);//(distance, speed, brake, wait, timer)
		liftUp(1400, 127, 15, 100, 3000);//(potValue, speed, hold, wait, timer)
		clawClose(3000, 127, 40);//(potValue, speed, hold)
		liftUp(1400, 127, 15, 100, 3000);//(potValue, speed, hold, wait, timer)
		bwds(150, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnRight(100, 80, 10, 100);//(distance, speed, brake, wait)
		bwds(1100, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftDown(1220, 127, 10, 200, 3000);//(potValue, speed, hold, wait, timer)
		liftControl(0);//(speed)

	}
	else if(autonNum == 9)//---BLUE_LEFT_20_POINT---//
	{

	}
	else if(autonNum == 10)//---RED_LEFT_20_POINT---//
	{
		liftControl(10);//(speed)
		fwds(1300, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		bwds(100, 80, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(90, 80, 10, 200);//(distance, speed, brake, wait)
		clawClose(3500, 100, 0);//(potValue, speed, hold)
		wait1Msec(500);
		clawOpen(3000, 100, 0);//(potValue, speed, hold)
		fwds(300, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawClose(2900, 127, 40);//(potValue, speed, hold)
		liftUp(1400, 127, 40, 100, 2000);//(potValue, speed, hold, wait, timer)
		bwds(200, 80, 10, 250, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(500, 80, 10, 250);//(distance, speed, brake, wait)
		fwds(1000, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnRight(80, 80, 10, 100);//(distance, speed, brake, wait)
		fwds(650, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		clawOpen(2500, 127, 10);//(potValue, speed, hold)
		liftDown(1300, 127, 10, 200, 3000);//(potValue, speed, hold, wait, timer)
		fwds(100, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftUp(1400, 127, 15, 100, 3000);//(potValue, speed, hold, wait, timer)
		clawClose(3000, 127, 40);//(potValue, speed, hold)
		bwds(50, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		turnLeft(100, 80, 10, 100);//(distance, speed, brake, wait)
		bwds(500, 127, 10, 500, 3000);//(distance, speed, brake, wait, timer)
		liftDown(1220, 127, 10, 200, 3000);//(potValue, speed, hold, wait, timer)
		liftControl(0);//(speed)
	}
}
