#define liftSensor SensorValue[liftPot]
#define flyWheelSensor SensorValue[flyWheelEncoder]
#define clawSensor SensorValue[clawPot]
#define ballTopSensor SensorValue[ballDetectorTop]
#define ballBottomSensor SensorValue[ballDetectorBottom]
#define leftBaseSensor SensorValue[leftBaseEncoder]
#define rightBaseSensor SensorValue[rightBaseEncoder]
#define tipSensor SensorValue[tipGyro]
